name: Convert Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: List files for debugging
        run: |
          echo "Listing all Markdown files:"
          find . -name '*.md'
          echo "Current directory structure:"
          ls -R

      - name: Convert Markdown to HTML
        run: |
          find . -name '*.md' | while read -r file; do
            htmlfile="${file%.md}.html"
            echo "Converting $file to $htmlfile"
            pandoc "$file" -o "$htmlfile" --extract-media .
            if [ $? -eq 0 ]; then
              echo "Successfully converted $file"
            else
              echo "Failed to convert $file"
              echo "Attempting to debug file: $file"
              ls -l "$file"
              echo "Current directory structure at failure point:"
              ls -R
            fi
          done

      - name: Commit HTML files
        if: success()
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add **/*.html
          git commit -m 'Automatically convert MD to HTML'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
