name: Convert Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pandoc
        run: sudo apt-get install pandoc -y

      - name: Convert Markdown to HTML
        run: |
          mkdir -p html
          for file in $(find . -name '*.md'); do
            pandoc "$file" -o "html/${file%.md}.html"
            mv "${file%.md}.html" ./html/
          done

      - name: Commit HTML files
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add html/*
          git commit -m 'Automatically convert MD to HTML'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
