name: Convert Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p html
          find . -name '*.md' | while read -r file; do
            htmlfile="html/${file%.md}.html"
            pandoc "$file" -o "$htmlfile" && echo "Converted $file to $htmlfile"
          done

      - name: Commit HTML files
        if: success()
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add html/*
          git commit -m 'Automatically convert MD to HTML'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
